"""Add price field to Item model

Revision ID: 0826cf3e3ceb
Revises: f0e5573cee43
Create Date: 2025-10-12 15:07:23.549152

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0826cf3e3ceb'
down_revision = 'f0e5573cee43'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.Float(), nullable=False, server_default='0.0'))


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_column('price')

    # ### end Alembic commands ###
