"""Added category and date_added columns to Item

Revision ID: f0e5573cee43
Revises: 050557c9b405
Create Date: 2025-10-10 16:02:47.108118

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0e5573cee43'
down_revision = '050557c9b405'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('supplier', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('date_added', sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_column('date_added')
        batch_op.drop_column('supplier')
        batch_op.drop_column('category')

    # ### end Alembic commands ###
